
# This is a basic workflow to help you get started with Actions

name: Notify on release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        uses: CommonMarvel/google-chat-notification@v1.1.1
        with:
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}