# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Pull Request
    runs-on: macos-latest
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Install dependancies
        run: npm install

      - name: Build project
        run: npm run pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
