# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Increment version
        run: npm version patch --no-git-tag-version

      - name: Install dependancies
        run: npm install
      
      - name: Prepare for app notarization
        run: |
            mkdir -p ~/private_keys/
            echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

      - name: Get package version
        id: package_version
        run: |
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g' \
            | tr -d '[[:space:]]')
          echo "$PACKAGE_VERSION"
          echo "::set-output name=PACKAGE_VERSION::$PACKAGE_VERSION"

      - uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ./build/Mac_Certificates.p12
          p12-password: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}

      - name: Build/release Electron app
        run: |
          ls ./build
          chmod +x ./dist.sh
          ./dist.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ./build/Mac_Certificates.p12
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}
          API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}

      - name: "Commit updated package.json to repo"
        uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          commit_message: "Created new package version"
          file_pattern: ./package*.json
          push_options: "--force"
